name: 🕷️ Bug report
description: Create a bug report to help the project improve
labels: ["bug"]
title: "[BUG] <title>"
body:
    - type: markdown
      attributes:
          value: |
              This issue form is for reporting bugs only!

              If you have a feature or enhancement request, please use the [feature request][fr] section of our [GitHub Discussions][fr].

              [fr]: https://github.com/seriousm4x/UpSnap/discussions/new?category=feature-requests

    - type: textarea
      validations:
          required: true
      attributes:
          label: The bug
          description: >-
              Describe the issue you are experiencing here. Tell us what you were trying to do and what happened.

              Provide a clear and concise description of what the problem is.

    - type: markdown
      attributes:
          value: |
              ## Environment

    - type: input
      validations:
          required: true
      attributes:
          label: The OS that UpSnap is running on
          placeholder: Ubuntu 22.10, Debian, Arch...

    - type: input
      id: version
      validations:
          required: true
      attributes:
          label: Version of UpSnap
          placeholder: 4.2.0

    - type: textarea
      validations:
          required: true
      attributes:
          label: Your docker-compose.yml content
          render: YAML

    - type: textarea
      id: repro
      attributes:
          label: Reproduction steps
          description: "How do you trigger this bug? Please walk us through it step by step."
          value: |
              1.
              2.
              3.
              ...
          render: bash
      validations:
          required: true

    - type: textarea
      attributes:
          label: Additional information
          description: >
              If you have any additional information for us, use the field below.
